### ISSUE TITLE
In OpenAPI 3.0, does not appear possible to receive files

### ISSUE THREAD

**Issue by hsunner** [commonism/aiopenapi3#108]
Any content-type except json causes a NotImplementedError. As I understand it this makes it impossible to download files (unless they are json).

Given the example showing how to download tar files (content-type application/octet-stream) in docs/source/plugin.rst, there must be support for other content-types in other implementations, but in aiopenapi3/v30/glue.py there is no such support.

The rest service I'm interfacing is not compliant to its own spec as it, depending on parameters, may return a csv file (as content-type application/octet-stream) instead of a json and this is not present in the spec. I am trying to modify the definition (hand-editing and using plugins) to match the behaviour, so it's perfectly possible I am misunderstanding something or doing something wrong. 

What I see is that as soon as I add an "application/octet-stream" definition under ["responses"]["200"]["content"] for an endpoint on my OpenAPI 3.0.1 spec I get the following error:
`
File "/Users/hampuss/dists/aiopenapi3/aiopenapi3/v30/glue.py", line 338, in _process
    raise NotImplementedError()`

That code looks like this (in method Request._process)
```python
if content_type.lower() == "application/json":
    ... # handling json responses
else:
    raise NotImplementedError()
```

**Comment by commonism** [comment]
Hi,

which version do you use?

… this is a work in progress but basics should be covered in 2.1
https://github.com/commonism/aiopenapi3/blob/master/tests/fixtures/paths-requestbody-formdata-encoding.yaml
https://github.com/commonism/aiopenapi3/blob/master/tests/formdata_test.py#L8

the pydanticv2 branch may have additional features - but is another work in progress.

**Comment by hsunner** [comment]
Thanks for the swift response.

I'm using the current HEAD on master (release 0.2.1 / 32085a7d).

I looking for this functionality for production (internal tool) late summer, so I'm prepared to put in some work for a PR. I will check the references you sent after vacation. If you have any further suggestion for how to implement, or assessment of the complexity, please let me know.

**Comment by hsunner** [comment]
To me, the fix appears as simple as replacing the final line in this truncated block ([aiopenapi3/v30/glue.py#L435](https://github.com/commonism/aiopenapi3/blob/32085a7d8a0d9db767e5d37fd1e58d6ae176d55e/aiopenapi3/v30/glue.py#L435)) 
```python
class Request(RequestBase):
    ...
    def _process(self, result):
        ...
        if content_type.lower() == "application/json":
            ...
        else:
            raise NotImplementedError()
``` 
with 
```python
class Request(RequestBase):
    ...
    def _process(self, result):
        ...
        if content_type.lower() == "application/json":
            ...
        else:
            return rheaders, ctx.received
```

However, I suspect there is a good reason for rasing the error that I don't understand. To me, returning the data as is would be expected behaviour if it has the expected content-type and is not possible to validate.

**Comment by commonism** [comment]
There was no good reason beyond not accepting anything but "application/json".
Your approach is right.

**Comment by hsunner** [comment]
Created a PR for that single-line change. Seems a bit silly, but it felt like the correct thing to do.

As far as I can tell, the behaviour in 3.0 schemas is now identical to that of 2.0 schemas. I could not find any comparable code in 3.1 schemas (or even the place where responses are validated). If you point out to me where it is I can try to make sure we have the same behaviour for OpenApi 3.1 schemas.

Don't know your policy on comments, but I included one that I might have included if it was my own code. Feel free to remove.
