### ISSUE TITLE
Factory Arguments

### ISSUE THREAD

**Issue by ggpwnkthx** [commonism/aiopenapi3#140]
https://github.com/commonism/aiopenapi3/blob/f955d57158caa189e657e48898164b41a1e09fec/aiopenapi3/request.py#L74-L75

I've run into a situation where I need to use a non-default `timeout` value in a session factory. There's currently no way to pass through factory arguments. To facilitate this, should a `factory_args` argument be added to the `OpenAPI` constructor, set as an object property, and have the `_factory_args` method unpack the property value? Or is there a better way to handle this?

**Comment by commonism** [comment]
_factory_args is the default set of parameters passed to the session factory:
https://github.com/commonism/aiopenapi3/blob/e4bbfcd987da49a05e73665342a623e9b229f70b/aiopenapi3/request.py#L88-L88

if you have your [own](https://aiopenapi3.readthedocs.io/en/latest/advanced.html#session-factory), you can extend/modify the default kw/args passed to httpx.Client 

e.g.
```python
def session_factory(*args, **kwargs) -> httpx.Client:
    return httpx.AsyncClient(*args, timeout=60.0, **kwargs)
```

**Comment by ggpwnkthx** [comment]
Ah, that makes way more sense. It's been a long day and I've been hyper focused. I'm silly. Thanks for point this out!
