### ISSUE TITLE
security scheme comparison should be case-insensitive

### ISSUE THREAD

**Issue by hsunner** [commonism/aiopenapi3#96]
The code in Request._prepare_secschemes() compares the component.securitySchemes[].scheme value case-sensitive to lower-case constants, but the names of security schemes are not case-sensitive in the OpenAPI spec. The situation is messy, but it seems RFC7235 sec2.1 is regarded as authoritative in which constants are case-insensitive. 

In addition, in the same code the component.securitySchemes[].bearerFormat value is used as a Python template string, which is incorrect. It is in fact a documentation hint to a human reader (e.g. to know that it is a JWT token that can be decoded).

I am prepared to make a PR for this (it's a 5 LOC change).

References:
https://github.com/OAI/OpenAPI-Specification/issues/1876
https://www.iana.org/assignments/http-authschemes/http-authschemes.xhtml
https://datatracker.ietf.org/doc/html/rfc7235#section-2.1

**Comment by commonism** [comment]
What do you think about using constr(to_lower=True) as annotation for scheme instead of adjusting the comparisons?
https://github.com/commonism/aiopenapi3/blob/master/aiopenapi3/v30/security.py#L45

**Comment by hsunner** [comment]
I will test that shortly. I'm currently validating my fix based on .lower(), but yours is a more abstract solution.

**Comment by hsunner** [comment]
Works well, once I understood what you envisaged. PR submitted. Thank's for the swift reply!
